source 'https://rubygems.org/'

gem 'librarian-puppet', '< 1.0'
gem 'puppet', '~> 3'
gem 'puppet-lint', '~> 1.0'
gem 'puppetlabs_spec_helper'
gem 'rake', '~> 10'
gem 'rspec', '~> 3'
gem 'rspec-puppet'
gem 'serverspec'
